language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer self-update
    - composer install --dev --no-interaction

script:
    - vendor/bin/phpunit -c test/phpunit.xml
    - php .travis/coverage-checker.php build/coverage-clover.xml 100
    - vendor/bin/phpcs --standard=PSR2 -s -p config/ src/ test/
    - vendor/bin/phpdoc -c phpdoc.xml --force

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
